name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  single-report-path:
    required: false
    description: 'Analyze a single report'
  individual-reports-folder:
    required: false
    description: 'The folder containing the downloaded individual rspec reports'
    default: 'individual-reports'
  output-report:
    required: false
    description: 'relative path to output report'
    default: 'rspec-split-config.json'
  group-count:
    required: false
    description: 'The number of groups to split the cucumber reports into'
  upload:
    required: false
    description: 'Uploads the report as an artifact'
    default: 'true'
  upload-name:
    required: false
    description: 'Name of the artifact'
    default: 'rspec-split-config'
runs:
  using: 'node16'
  main: 'dist/index.js'
